ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "neq" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "isValidated" BOOLEAN DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;
